### ISSUE TITLE
Reorganize configs to support a YAML configuration format

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jenkins-bootstrap-shared#3]
YAML configuration should follow a convention for templates.

```yaml
#configures jenkins settings through convention
#if a String, then executes a simple script
#if a Map or List then executes the script following a binding naming convention

settings:
    - 'configure_csrf_protection'
    - 'configure_master_settings':
          'admin_email': 'email@example.com'
          'jnlp_slave_port': 9000
          'labels': 'jervis_generator'
```

It should call the following scripts and pass settings to it automatically:

```
scripts/configure-csrf-protection.groovy
scripts/configure-master-settings.groovy
```

The bindings in Groovy for settings by convention should be:

```groovy
configure_master_settings = [
    'admin_email': 'email@example.com',
    'jnlp_slave_port': 9000,
    'labels': 'jervis_generator'
]
```
